language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
addons:
  apt:
    packages:
      - xserver-xephyr
jobs:
  include:
  - python: 3.6
    env: TOXENV=lint
install:
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
